/*Modelagem Básica -  
ENTIDADE = TABELA
CAMPOS = ATRIBUTOS*/

Cliente

Nome(CHARACTER(30))
CPF(NUMERIC(11))
Email(CHARACTER(30))
Telefone (CHARACTER(30))
Endereco(CHARACTER(100))
Sexo(CHARACTER(1))

/* Processos de modelagem */

/*FASE 01 E 02 - FEITAS PELO AD (ADMINISTRADOR DE DADOS) 

Modelagem conceitual - RASCUNHO
Modelagem Lógica - QUALQUER PROGRAMA DE MODELAGEM


/*FASE 03 - FEITAS PELO DBA/AD */

Modelagem fisica - SCRIPTS DE BANCO


/*CRIANDO BANCO DE DADOS -  FASE 04*/

CREATE DATABASE PROJETOINICIAL;



/* CONECTANDO AO BANCO DE DADOS - FASE 05*/

USE PROJETOINICIAL;


/* CRIANDO TABELA DE CLIENTES */

CREATE TABLE CLIENTES(
NOME VARCHAR(30),
SEXO CHAR(1),
EMAIL VARCHAR(30),
CPF INTEGER(11),
TELEFONE VARCHAR(30),
ENDERECO VARCHAR(100)

);


/* MOstrar tabelas    */

show tables;

/* Descobrindo como é a estrutura de uma tabela */

desc cliente;
	
/*Inserindo informações na tabelas(SEM DESCREVER AS COLUNAS) - INSERT INTO 'TABELA' VALUES*/

INSERT INTO CLIENTES VALUES ('EDIANDRO','M','EDFC18@GMAIL.COM',1285798473,'22988206561','LUZIA VIEIRA HENRIQUES,265');
INSERT INTO CLIENTES VALUES ('LEANDRO','M','XEREKA@GMAIL.COM',578466866,'22988000000','LUZIA VIEIRA HENRIQUES,265');
INSERT INTO CLIENTES VALUES ('LUCIA','M','PELASACO@GMAIL.COM',1285798,'22988211111','LUZIA VIEIRA HENRIQUES,265');

/*Inserindo informações na tabelas(DESCREVENDO AS COLUNAS) - INSERT INTO 'TABELA'(NOME DOS CAMPOS) VALUES(); */

INSERT INTO CLIENTES(NOME,SEXO,CPF,TELEFONE,ENDERECO) VALUES('BERNARDO','M',55448899,'38242424','RUA DO CAPETA,MATADOURO- 265');

/* COMANDO SELECT - SELECAO, PROJECAO E JUNCAO */

SELECT NOW();
SELECT 'EDIANDRO FERREIRA';
SELECT 'BANCO DE DADOS';

/* ALIAS DE COLUNAS */

SELECT NOME,SEXO,EMAIL FROM CLIENTES;
SELECT NOME AS CLIENTE,SEXO,EMAIL,ENDERECO,CPF FROM CLIENTES;
SELECT NOME AS CLIENTE,SEXO,EMAIL,ENDERECO,CPF, NOW() AS DATA_HORA FROM CLIENTES


/*FILTRANDO COM WHERE E LIKE*/ -- IMPORTANTE, PARA PROJEÇÃO = SELECT, PARA SELECT=WHERE **LEMBRAR**

SELECT NOME AS CLIENTE, SEXO AS GENERO FROM CLIENTES 
WHERE SEXO='M';

SELECT NOME AS CLIENTES, ENDERECO FROM CLIENTES
WHERE SEXO='F';

SELECT NOME AS CLIENTE FROM CLIENTES WHERE SEXO = 'F';

/* UTILIZANDO O LIKE*/

SELECT NOME AS CLIENTE, SEXO AS GENÊRO FROM CLIENTES WHERE ENDERECO LIKE '265';

/* CARACTER CORINGA '%' - O PERCENT SIGNIFICA QUALQUER COISA*/

SELECT NOME, SEXO, ENDERECO FROM CLIENTES WHERE ENDERECO LIKE '%265'; /* QUALQUER COISA E '265'*/
SELECT NOME, SEXO FROM CLIENTES WHERE ENDERECO LIKE 'LUZIA%'; /* 'LUZIA' E QUALQUER COISA */
SELECT NOME, SEXO FROM CLIENTES WHERE ENDERECO LIKE '%VIEIRA%'; /* 'VIEIRA' DENTRO DE QUALQUER COISA */


/* DESAFIO DO EXERCICIO - EDITORA*/

CREATE DATABASE LIVRARIA;

CREATE TABLE LIVROS(

NOMELIVRO VARCHAR(50),
NOMEAUTOR VARCHAR(50),
SEXOAUTOR CHAR (1),
NUMPAGINAS INT(5),
NOMEEDITORA VARCHAR(20),
VALORLIVRO FLOAT(6),
UFEDITORA CHAR(2),
ANOPUBLICACAO CHAR(4)
);

/* INSERINDO OS DADOS NA TABELA DE ACORDO COM DESAFIO*/

INSERT INTO LIVROS(NOMELIVRO,NOMEAUTOR,SEXOAUTOR,NUMPAGINAS,NOMEEDITORA,VALORLIVRO,UFEDITORA,ANOPUBLICACAO) 
VALUES('Cavaleiro Real','Ana Claudia','F',465,'Atlas',49.5,'RJ',2009),
('SQL para leigos','João Nunes', 'M',450,'Addison',98,'SP',2018),
('Receitas Caseiras','Celia Tavares','F',210,'Atlas',45,'RJ',2008),
('Pessoas Efetivas','Eduardo Santos','M',390,'Beta',78.99,'RJ',2018),
('Habitos Saudáveis','Eduardo Santos','M',630,'Beta',150.98,'RJ',2019),
('A Casa Marrom','Hermes Macedo','M',250,'Bubba',60,'MG',2016),
('Estacio Querido','Geraldo Francisco','M',310,'Insignia',100,'ES',2015),
('Pra sempre amigas','Leda Silva','F',510,'Insignia',78.98,'ES',2011),
('Copas Inesqueciveis','Marco Alcantara','M',200,'Larson',130.98,'RS',2018),
('O poder da mente','Clara Mafra','F',120,'Continental',56.58,'SP',2017);

/* 1-TRAZER TODOS OS DADOS*/
SELECT * FROM LIVROS;

/* 2- TRAZER O NOME DO LIVRO E O NOME DA EDITORA */
SELECT NOMELIVRO,NOMEEDITORA FROM LIVROS;

/* 3- TRAZER O NOME DO LIVRO E A UF DOS LIVROS PUBLICADOS POR AUTORES DO SEXO MASCULINO.*/
SELECT NOMELIVRO AS LIVRO, UFEDITORA AS ESTADO FROM LIVROS WHERE SEXOAUTOR='M';

/* 4- TRAZER O NOME DO LIVRO E O NUM DE PAGINAS DOS LIVROS PUBLICADOS POR AUTORES DO SEXO FEMININO. */
SELECT NOMELIVRO AS LIVRO, NUMPAGINAS AS TOTALPÁGINAS FROM LIVROS WHERE SEXOAUTOR='F';

/* 5- TRAZER OS VALORES DOS LIVROS DAS EDITORAS DE SÃO PAULO. */
SELECT NOMELIVRO AS LIVRO,VALORLIVRO AS PREÇOLIVRO FROM LIVROS WHERE UFEDITORA='SP';

/* 6- TRAZER OS DADOS DOS AUTORES DO SEXO MASCULINO QUE TIVERAM LIVROS PUBLICADOS POR SP OU RJ.(DESAFIO DO PROJETO)*/
SELECT NOMEAUTOR,NOMELIVRO,NOMEEDITORA,UFEDITORA,SEXOAUTOR FROM LIVROS WHERE SEXOAUTOR ='M' AND UFEDITORA ='RJ' OR UFEDITORA='SP';


/* TABELA VERDADE */

Revisar depois


/* Count(*), GROUP BY, PERFORMANCE COM OPERADORES LÓGICOS */

/* CONTANDO OS REGISTROS DE UMA TABELA */

SELECT COUNT(*) AS 'QTD REGISTROS TABELA CLIENTE' FROM CLIENTES;

/* OPERADOR GROUP BY */

SELECT SEXO , COUNT(*) 
FROM CLIENTES
GROUP BY SEXO;

/* PERFORMANCE COM OPERADORES LOGICOS */

NAS QUERYS COM OPERADOR LOGICO 'OR', USAR O STATEMENT QUE TEM MAIOR PROBABILIDADE DE ACONTECER EM PRIMEIRO LUGAR;
NAS QUERYS COM OPERADOR LOGICO 'AND', USA O STATEMENT COM MENOR PROBABILIDADE DE ACONTECER PRIMEIRO.


/*EXERCICIO 2.0*/

/*CRIAR UMA NOVA DATABASE 'EXERCICIO'*/
CREATE DATABASE EXERCICIO;

/*CRIANDRO TABELA FUNCIONARIOS*/

CREATE TABLE FUNCIONARIOS(
IDFUNCIONARIO INTEGER,
NOME VARCHAR(100),
EMAIL VARCHAR(200),
SEXO VARCHAR(10), 
DEPARTAMENTO VARCHAR(100),
ADMISSAO VARCHAR(10),
SALARIO INTEGER,
CARGO VARCHAR (100),
IDREGIAO INT
);

/* Considerando o que vc aprendeu sobre performance, resolva os exercicios abaixo */

/* TRAGA OS FUNCIONARIOS QUE TRABALHEM NO DEPARTAMENTO DE FILMES OU NO DEPARTAMENTO DE ROUPAS  - 21 | Filmes   53 | Roupas */

OBS.; COMO É O OPERADOR LOGICO 'OR', POR QUESTÃO DE MELHOR PERFORMANCE DO BD, É MELHOR COLOCAR O STATEMENT QUE TEM MAIOR 
CONDIÇÃO DE SER VERDADEIRO PRIMEIRO!

SELECT DEPARTAMENTO, COUNT(*)AS QUANTIDADE FROM FUNCIONARIOS 
WHERE DEPARTAMENTO='ROUPAS' OR DEPARTAMENTO='FILMES'
GROUP BY DEPARTAMENTO;

/* O GESTOR DE MKT PEDIU A LISTA DAS FUNCIONARIAS QUE TRABALHEM NO DPT DE FILMES OU NO DPT LAR. ELE NECESSITA ED ENVIAR UM EMAIL
PARA AS COLABORADORAS DESSES DOIS SETORES - OBS.: LAR=52 E FILMES= 21 */

SELECT SEXO AS GENERO, COUNT(*) AS 'QTD' FROM FUNCIONARIOS
GROUP BY SEXO;


SELECT NOME,SEXO EMAIL, DEPARTAMENTO FROM FUNCIONARIOS
WHERE SEXO = 'FEMININO' AND (DEPARTAMENTO='LAR' OR DEPARTAMENTO = 'FILMES')
ORDER BY DEPARTAMENTO;
/*ESSA QUERY ABAIXO ESTA USANDO O TERMO 'TUNNING', PRA QUERY SER MAIS OBJETIVA NA PESQUISA E GASTAR MENOS MEMÓRIA*/
SELECT NOME,SEXO,DEPARTAMENTO FROM FUNCIONARIOS
WHERE (DEPARTAMENTO='LAR' AND SEXO='FEMININO') OR (DEPARTAMENTO='FILMES' AND SEXO='FEMININO')
ORDER BY 1;


/* TRAGA OS FUNC DO SEXO MASCULINO OU OS QUE TRABALHEM NO SETOR JARDIM - MASCULINO=484 E JARDIM = 47 */

SELECT *, COUNT(*) FROM FUNCIONARIOS
WHERE SEXO='MASCULINO';
--GROUP BY NOME;

SELECT *, COUNT(*) FROM FUNCIONARIOS
WHERE DEPARTAMENTO='JARDIM';

SELECT NOME,SEXO,DEPARTAMENTO FROM FUNCIONARIOS
WHERE SEXO='MASCULINO' OR DEPARTAMENTO='JARDIM';

/*TRAZER VALORES NULOS*/
SELECT NOME,EMAIL FROM CLIENTES
WHERE EMAIL IS NULL;
/*TRAZENDO VALORES NÃO VAZIOS*/
SELECT NOME,EMAIL FROM CLIENTES
WHERE EMAIL IS NOT NULL;


/*UTILIZANDO O COMANDO UPDATE PARA ATUALIZAR VALORES NA TABELA*/

UPDATE CLIENTES 
SET EMAIL='CHAVASCANORABO@GMAIL.COM'
WHERE NOME='BERNARDO';

/* UTILIZANDO O DELETE PARA DELETAR REGISTROS*/
/*FAZER SEMPRE UM SELECT PARA CONTAR OS DADOS ACHADO, PARA QUANDO FOR DELETAR OS REGISTROS, TER O MESMO VALOR DELETADO*
QUE FOI ACHADO NO SELECT*/

--DELETAR REGISTROS DA ANA--

SELECT *, COUNT(*) FROM CLIENTES
WHERE NOME='LUCIA'; --TOTAL DE 1 REGISTRO--

DELETE FROM CLIENTES
WHERE NOME='LUCIA';

SELECT *,COUNT(*) FROM CLIENTES;

INSERT INTO CLIENTES VALUES('CARLA','F','C.LOPES@GMAIL.COM',45486585,'22984615678','RUA DO SACI -ITAPERUNA RJ');

/*DELETANDO UM REGISTRO COM DUAS PROPOSIÇÕES - USAR QUANDO TEM REGISTROS COM OS MESMOS NOMES*/

--SELECT-- 
SELECT * FROM CLIENTES
WHERE NOME='CARLA'
AND EMAIL='C.LOPES@GMAIL.COM';
--DELETE--
DELETE FROM CLIENTES
WHERE NOME='CARLA'
AND EMAIL='C.LOPES@GMAIL.COM';

/*Primeiro forma normal*/

/* 1- Todo campo vetorizado, se tornara outra tabela

[amarelo,azul,vermelho,branco,preto] - vetor de cores
[uno,gol,jeep,civic,fiesta,corolla] - vetor de carros


2- Todo campo multivalorado, se tornara outra tabela. Quando o campo for divisivel!

3- Toda tabela necessita de pelo menos um campo que identifique todo o registro, como sendo unico.
Isso é oque chamamos de chave primaria ou primary key.

*/

@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
/* CARDINALIDADE */


/* IMPORTANTE: QUEM DEFINE A CARDINALIDADE É A REGRA DE NEGOCIO */

/* O PRIMEIRO ALGARISMO - DEFINE OBRIGATORIEDADE 
0- NÃO OBRIGATORIO
1- OBRIGATORIO
*/

/* O SEGUNDO ALGARISMO - CARDINALIDADE
1 - MAXIMO UM
N - MAIS DE UM
*/
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

CREATE DATABASE COMERCIO;

USE COMERCIO;

CREATE TABLE CLIENTE(
IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
NOME VARCHAR(100) NOT NULL,
SEXO ENUM('M','F') NOT NULL,
EMAIL VARCHAR(100) UNIQUE,
CPF VARCHAR(15) UNIQUE
);

CREATE TABLE ENDERECO(
IDENDERECO INT PRIMARY KEY AUTO_INCREMENT,
RUA VARCHAR(100) NOT NULL,
BAIRRO VARCHAR(30) NOT NULL,
CIDADE VARCHAR(30) NOT NULL,
ESTADO CHAR(2) NOT NULL,
ID_CLIENTE INT UNIQUE, /* O UNIQUE INDICA QUE O RELACIONAMENTO DE CLIENTES PARA ENDERECO É 1X1*/
FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(IDCLIENTE)
);

CREATE TABLE TELEFONE(
IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT,
TIPO ENUM('RES','COM','CEL') NOT NULL,
NUMERO VARCHAR(10) NOT NULL,
ID_CLIENTE INT, /* COMO O RELACIONAMENTO DE CLIENTE PARA TELEFONE É 1XN, NAO PRECISA DO UNIQUE*/
FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTE(IDCLIENTE)
);

/* ENDERECO - OBRIGATORIO
CADASTRO DE SOMENTE UM.

CADASTRO - NAO OBRIGATORIO
CADASTRO DE MAIS DE UM(OPCIONAL)*/

/* CHAVE ESTRANGEIRA OU FOREIGN KEY, É A CHAVE PRIMARIA 
OU PRIMARY KEY, DE UMA TABELA ORIGEM E VAI ATE OUTRA TABELA 
DESTINO. PARA QUE POSSA FAZER REFERENCIA ENTRE OS REGISTROS.
*/

/*CONCEITO DE TABELA FORTE E TABELA FRACA*/

/* EM RELACIONAMENTO DE 1X1, A CHAVE ESTRANGEIRA FICA
NA TABELA MAIS FRACA*/

/* EM RELACIONAMENTO DE 1XN, A CHAVE ESTRANGEIRA FICA
NA TABELA COM CARDINALIDADE N*/


/* APAGAR TABELAS*/

DROP TABLE 'NOMEDATABELA';


INSERT INTO CLIENTE VALUES(NULL, 'FERREIRA', 'M','FER@GMAIL.COM','4564984731');
INSERT INTO CLIENTE VALUES(NULL, 'LUCIA', 'F','CHAMA@GMAIL.COM','12456451');
INSERT INTO CLIENTE VALUES(NULL, 'ELIZEU', 'M','FOGO@GMAIL.COM','128331');
INSERT INTO CLIENTE VALUES(NULL, 'LEANDRO', 'M','AR@GMAIL.COM','1285221');
INSERT INTO CLIENTE VALUES(NULL, 'AMANDA', 'F','KEKW@GMAIL.COM','111984731');
INSERT INTO CLIENTE VALUES(NULL, 'ADILTON', 'M','FARINHA@GMAIL.COM','128004731');
INSERT INTO CLIENTE VALUES(NULL, 'ADEMILTON', 'M','FEIJAO8@GMAIL.COM','1211731');
INSERT INTO CLIENTE VALUES(NULL, 'SHAKAL', 'M','KUK@GMAIL.COM','12857661');
INSERT INTO CLIENTE VALUES(NULL, 'BETHOVEN', 'M','PENISLONGO@GMAIL.COM','1255731');
INSERT INTO CLIENTE VALUES(NULL, 'CHIQUITA','F','KAKAKA@GMAIL.COM','1288731');
INSERT INTO CLIENTE VALUES(NULL, 'AMORA', 'F','KEKEK@GMAIL.COM','1285710101');
INSERT INTO CLIENTE VALUES(NULL, 'FLAVIA', 'F','KIKIKI@GMAIL.COM','128831');
INSERT INTO CLIENTE VALUES(NULL, 'FLOR DE LIS', 'F','COOCOC@GMAIL.COM','12855731');
INSERT INTO CLIENTE VALUES(NULL, 'WINDERSON NUNES', 'M','LARISSAKENGA@GMAIL.COM','127878731');
INSERT INTO CLIENTE VALUES(NULL, 'VITAO TALARICO', 'M','CAMILAPAMONHA@GMAIL.COM','128654731');
INSERT INTO CLIENTE VALUES(NULL, 'LUISA SONZA', 'F','CAROLDEBILMENTAL@GMAIL.COM','12868731');
INSERT INTO CLIENTE VALUES(NULL, 'ALEK', 'M','RAFAELTALARICO@GMAIL.COM','984731');
INSERT INTO CLIENTE VALUES(NULL, 'ZOIO', 'M','PAIXAO@GMAIL.COM','121');
INSERT INTO CLIENTE VALUES(NULL, 'DAMARES', 'F','LOUCURA@GMAIL.COM','8536531');



+-----------+-------------------+------+----------------------------+-------------+
| IDCLIENTE | NOME              | SEXO | EMAIL                      | CPF         |
+-----------+-------------------+------+----------------------------+-------------+
|         1 | EDIANDRO FERREIRA | M    | EDFC18@GMAIL.COM           | 12857984731 |
|         2 | FERREIRA          | M    | FER@GMAIL.COM              | 4564984731  |
|         3 | LUCIA             | F    | CHAMA@GMAIL.COM            | 12456451    |
|         4 | ELIZEU            | M    | FOGO@GMAIL.COM             | 128331      |
|         5 | LEANDRO           | M    | AR@GMAIL.COM               | 1285221     |
|         6 | AMANDA            | F    | KEKW@GMAIL.COM             | 111984731   |
|         7 | ADILTON           | M    | FARINHA@GMAIL.COM          | 128004731   |
|         8 | ADEMILTON         | M    | FEIJAO8@GMAIL.COM          | 1211731     |
|         9 | SHAKAL            | M    | KUK@GMAIL.COM              | 12857661    |
|        10 | BETHOVEN          | M    | PENISLONGO@GMAIL.COM       | 1255731     |
|        11 | CHIQUITA          | F    | KAKAKA@GMAIL.COM           | 1288731     |
|        12 | AMORA             | F    | KEKEK@GMAIL.COM            | 1285710101  |
|        13 | FLAVIA            | F    | KIKIKI@GMAIL.COM           | 128831      |
|        14 | FLOR DE LIS       | F    | COOCOC@GMAIL.COM           | 12855731    |
|        15 | WINDERSON NUNES   | M    | LARISSAKENGA@GMAIL.COM     | 127878731   |
|        16 | VITAO TALARICO    | M    | CAMILAPAMONHA@GMAIL.COM    | 128654731   |
|        17 | LUISA SONZA       | F    | CAROLDEBILMENTAL@GMAIL.COM | 12868731    |
|        18 | ALEK              | M    | RAFAELTALARICO@GMAIL.COM   | 984731      |
|        19 | ZOIO              | M    | PAIXAO@GMAIL.COM           | 121         |
|        20 | DAMARES           | F    | LOUCURA@GMAIL.COM          | 8536531     |
+-----------+-------------------+------+----------------------------+-------------+

INSERT INTO ENDERECO VALUES(NULL, 'RUA DO CAPO', 'MATADOURO','ITAPERUNA','RJ',18);
INSERT INTO ENDERECO VALUES(NULL, 'RUA DO CAPITOLIO', 'NITEROI','ITALVA','RJ',6);
INSERT INTO ENDERECO VALUES(NULL, 'RUA DO JOAQUIM', 'CAPELA','PORCIUNCULA','RJ',10);
INSERT INTO ENDERECO VALUES(NULL, 'RUA DA TILAPIA', 'JOANA DARK','MASSACHUCETS','SP',11);
INSERT INTO ENDERECO VALUES(NULL, 'AV. CARDOSO MOREIRA', 'CENTRO','ITAPERUNA','RJ',13);
INSERT INTO ENDERECO VALUES(NULL, 'AV. CHULAPA', 'LUCULO','ITAPEMIRIM','ES',16);



INSERT INTO TELEFONE VALUES (NULL, 'CEL','9599896',3);
INSERT INTO TELEFONE VALUES (NULL, 'COM','9599896',5);
INSERT INTO TELEFONE VALUES (NULL, 'RES','9599896',7);
INSERT INTO TELEFONE VALUES (NULL, 'COM','9599896',9);
INSERT INTO TELEFONE VALUES (NULL, 'CEL','9599896',15);
INSERT INTO TELEFONE VALUES (NULL, 'RES','9599896',18);

INSERT INTO TELEFONE VALUES (NULL, 'CEL','9599896',3);
INSERT INTO TELEFONE VALUES (NULL, 'COM','9599896',3);
INSERT INTO TELEFONE VALUES (NULL, 'RES','9599896',3);
INSERT INTO TELEFONE VALUES (NULL, 'COM','9599896',7);
INSERT INTO TELEFONE VALUES (NULL, 'CEL','9599896',7);
INSERT INTO TELEFONE VALUES (NULL, 'RES','9599896',7);

****************************************************************************

/*SELEÇÃO, PROJEÇÃO E JUNÇÃO*/

/* PROJEÇÃO - É TUDO OQUE VC QUER VER NA TELA
EXEMPLOS:
*/

SELECT NOW() AS DATA_E_HORA;

SELECT 2*2 AS MULTIPLICACAO;

SELECT 2*2 AS MULTIPLICACAO,TIPO,NOW() AS DATA FROM TELEFONE;


/*SELEÇÃO - É QUANDO USA O WHERE. A SELEÇÃO USA UM FILTRO!
SUBCONJUNTO DO TOTAL DE REGISTROS DA TABELA.
EXEMPLOS:
*/

SELECT IDCLIENTE,NOME /*PROJEÇÃO*/ 
FROM CLIENTE /*ORIGEM*/
WHERE SEXO='F'; /*SELEÇÃO*/

SELECT TIPO,NUMERO /*PROJEÇÃO*/
FROM TELEFONE /*ORIGEM*/
WHERE TIPO='RES'; /*SELEÇÃO*/

************************************************************************

/* JUNÇÃO -> JOIN - INNER JOIN SIGNIFICA JUNÇÃO INTERNA, PEGA OS DADOS IGUAIS DE
DENTRO DE UMA TABELA DE CONJUNTOS */

/*INFORMAÇÕES DAS TABELAS CLIENTE E ENDEREÇO*/

SELECT NOME,SEXO,BAIRRO,CIDADE /*PROJEÇÃO*/
FROM CLIENTE /* ORIGEM */
INNER JOIN ENDERECO /*JUNÇÃO*/
ON IDCLIENTE=ID_CLIENTE; /*CONDIÇÃO*/
WHERE SEXO='F';

/*INFORMAÇÕES DAS TABELAS CLIENTE E TELEFONE*/

SELECT NOME,SEXO,EMAIL,TIPO,NUMERO /*PROJEÇÃO*/
INNER JOIN TELEFONE /* JUNÇÃO */
ON IDCLIENTE=ID_CLIENTE /* CONDIÇÃO DA JUNÇÃO */
WHERE TIPO='CEL'; /* SELEÇÃO */

/*NOME,BAIRRO,CIDADE,TIPO E NUMERO*
OBS.: AQUI TIVE UM PROBLEMA COM FOREIGN KEY IGUAIS EM TABELAS DIFERENTES,
ABAIXO ESTA O EXEMPLO DE COMO SE RESOLVER
*/

SELECT CLIENTE.NOME,ENDERECO.BAIRRO,ENDERECO.CIDADE,TELEFONE.TIPO,TELEFONE.NUMERO
FROM CLIENTE
INNER JOIN ENDERECO
ON CLIENTE.IDCLIENTE=.ENDERECO.ID_CLIENTE
INNER JOIN TELEFONE
ON CLIENTE.IDCLIENTE=TELEFONE.ID_CLIENTE; 

/*OU POSSO NOMEAR AS TABELAS NA CONSTRUÇÃO NO INNER JOIN - PONTERAMENTO*/

SELECT C.NOME,E.BAIRRO,E.CIDADE,T.TIPO,T.NUMERO
FROM CLIENTE C
INNER JOIN ENDERECO E
ON C.IDCLIENTE=E.ID_CLIENTE
INNER JOIN TELEFONE T
ON C.IDCLIENTE=T.ID_CLIENTE; 



/* 
	DML - DATA MANIPULATION LANGUAGE
	DDL - DATA DEFINITION LANGUAGE
	DCL - DATA CONTROL LANGUAGE
	TCL - TRANSACTION CONTROL LANGUAGE  
*/

/*DML - É A MANIPULAÇÃO DOS DADOS, INSERT, FILTROS,UPDATE,DELETE*/

*******************************************************************
/*DDL - DEFINIÇÃO DOS DADOS*/

CREATE TABLE PRODUTO(
IDPRODUTO INT PRIMARY KEY AUTO_INCREMENT,
NOMEPRODUTO VARCHAR(30) NOT NULL,
PRECO INT NOT NULL,
FRETE FLOAT(10,2) NOT NULL
);

/*ALTER TABLE -  COMANDO QUE SE ENCAIXA NO DDL*/

/*ALTERANDO O NOME DA TABELA USANDO CHANGE*/

ALTER TABLE PRODUTO
CHANGE PRECO PRECO_UNITARIO INT NOT NULL;

/* MODIFY - USADO PARA ALTERAR O TIPO DA VARIAVEL*/

ALTER TABLE PRODUTO
MODIFY PRECO_UNITARIO VARCHAR(30);

/* ADICIONANDO UM CAMPO NA TABELA - ADD*/

ALTER TABLE PRODUTO
ADD PESO FLOAT(10,2) NOT NULL;

/* APAGANDO COLUNA  - DROP COLUMN*/

ALTER TABLE PRODUTO
DROP COLUMN PESO;

/*ADICIONANDO COLUNA E SETANDO SUA POSIÇÃO NA TABELA - FIRST OU AFTER*/

ALTER TABLE PRODUTO
ADD COLUMN TAMANHO ENUM('P','M','G') NOT NULL
AFTER NOMEPRODUTO;

ALTER TABLE PRODUTO
DROP COLUMN TAMANHO;

ALTER TABLE PRODUTO
ADD COLUMN TAMANHO ENUM('P','M','G') NOT NULL
FIRST;

***********************************************************
/*DML DATA MODIFY LANGUAGE*/